# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import schedule_pb2 as schedule__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

#ce fichier contient les éléments relatifs aux stub du client et du serveur
# Avec gRPC le stub du client est appelé le stub alors que le stub du serveur est appelé le servicer

#Pour chaque méthode/procédure du service précisé dans le fichier proto initial, un attribut portant le même nom est 
#ajouté à l’objet MovieStub. Ce sont ces attributs que notre client devra appeler pour effectuer des appels distants au service. 
#L’attribut créé une connexion avec le serveur en utilisant l’input channel (4 types possibles unary_unary, unary_stream, 
#stream_unary et stream_stream).

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in schedule_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScheduleStub(object):
    """Missing associated documentation comment in .proto file."""
    #créer ses connexions avec le serveur
    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllSchedules = channel.unary_unary(
                '/schedule.Schedule/GetAllSchedules',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=schedule__pb2.ListSchedulesResponse.FromString,
                _registered_method=True)
        self.GetScheduleByDate = channel.unary_unary(
                '/schedule.Schedule/GetScheduleByDate',
                request_serializer=schedule__pb2.DateRequest.SerializeToString,
                response_deserializer=schedule__pb2.ScheduleEntry.FromString,
                _registered_method=True)
        self.CreateSchedule = channel.unary_unary(
                '/schedule.Schedule/CreateSchedule',
                request_serializer=schedule__pb2.CreateScheduleRequest.SerializeToString,
                response_deserializer=schedule__pb2.ScheduleEntry.FromString,
                _registered_method=True)
        self.UpdateSchedule = channel.unary_unary(
                '/schedule.Schedule/UpdateSchedule',
                request_serializer=schedule__pb2.UpdateScheduleRequest.SerializeToString,
                response_deserializer=schedule__pb2.ScheduleEntry.FromString,
                _registered_method=True)
        self.DeleteSchedule = channel.unary_unary(
                '/schedule.Schedule/DeleteSchedule',
                request_serializer=schedule__pb2.DateRequest.SerializeToString,
                response_deserializer=schedule__pb2.DeleteScheduleResponse.FromString,
                _registered_method=True)
        self.GetBestRatedMovie = channel.unary_unary(
                '/schedule.Schedule/GetBestRatedMovie',
                request_serializer=schedule__pb2.DateRequest.SerializeToString,
                response_deserializer=schedule__pb2.BestRatedResponse.FromString,
                _registered_method=True)


class ScheduleServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllSchedules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScheduleByDate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBestRatedMovie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScheduleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllSchedules': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllSchedules,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=schedule__pb2.ListSchedulesResponse.SerializeToString,
            ),
            'GetScheduleByDate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScheduleByDate,
                    request_deserializer=schedule__pb2.DateRequest.FromString,
                    response_serializer=schedule__pb2.ScheduleEntry.SerializeToString,
            ),
            'CreateSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSchedule,
                    request_deserializer=schedule__pb2.CreateScheduleRequest.FromString,
                    response_serializer=schedule__pb2.ScheduleEntry.SerializeToString,
            ),
            'UpdateSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSchedule,
                    request_deserializer=schedule__pb2.UpdateScheduleRequest.FromString,
                    response_serializer=schedule__pb2.ScheduleEntry.SerializeToString,
            ),
            'DeleteSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSchedule,
                    request_deserializer=schedule__pb2.DateRequest.FromString,
                    response_serializer=schedule__pb2.DeleteScheduleResponse.SerializeToString,
            ),
            'GetBestRatedMovie': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBestRatedMovie,
                    request_deserializer=schedule__pb2.DateRequest.FromString,
                    response_serializer=schedule__pb2.BestRatedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'schedule.Schedule', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('schedule.Schedule', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Schedule(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllSchedules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/schedule.Schedule/GetAllSchedules',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            schedule__pb2.ListSchedulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScheduleByDate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/schedule.Schedule/GetScheduleByDate',
            schedule__pb2.DateRequest.SerializeToString,
            schedule__pb2.ScheduleEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/schedule.Schedule/CreateSchedule',
            schedule__pb2.CreateScheduleRequest.SerializeToString,
            schedule__pb2.ScheduleEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/schedule.Schedule/UpdateSchedule',
            schedule__pb2.UpdateScheduleRequest.SerializeToString,
            schedule__pb2.ScheduleEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/schedule.Schedule/DeleteSchedule',
            schedule__pb2.DateRequest.SerializeToString,
            schedule__pb2.DeleteScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBestRatedMovie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/schedule.Schedule/GetBestRatedMovie',
            schedule__pb2.DateRequest.SerializeToString,
            schedule__pb2.BestRatedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
