# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schedule.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'schedule.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

# ce fichier contient le code relatif aux types de messages et le serializer et deserializer des informations

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eschedule.proto\x12\x08schedule\x1a\x1bgoogle/protobuf/empty.proto\"\x1b\n\x0b\x44\x61teRequest\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"-\n\rScheduleEntry\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"C\n\x15ListSchedulesResponse\x12*\n\tschedules\x18\x01 \x03(\x0b\x32\x17.schedule.ScheduleEntry\"5\n\x15\x43reateScheduleRequest\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"5\n\x15UpdateScheduleRequest\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06movies\x18\x02 \x03(\t\"j\n\x16\x44\x65leteScheduleResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12.\n\rdeleted_entry\x18\x03 \x01(\x0b\x32\x17.schedule.ScheduleEntry\"D\n\x05Movie\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06rating\x18\x03 \x01(\x01\x12\x10\n\x08\x64irector\x18\x04 \x01(\t\"b\n\x11\x42\x65stRatedResponse\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x1e\n\x05movie\x18\x02 \x01(\x0b\x32\x0f.schedule.Movie\x12\x0e\n\x06rating\x18\x03 \x01(\x01\x12\x0f\n\x07message\x18\x04 \x01(\t2\xc7\x03\n\x08Schedule\x12J\n\x0fGetAllSchedules\x12\x16.google.protobuf.Empty\x1a\x1f.schedule.ListSchedulesResponse\x12\x43\n\x11GetScheduleByDate\x12\x15.schedule.DateRequest\x1a\x17.schedule.ScheduleEntry\x12J\n\x0e\x43reateSchedule\x12\x1f.schedule.CreateScheduleRequest\x1a\x17.schedule.ScheduleEntry\x12J\n\x0eUpdateSchedule\x12\x1f.schedule.UpdateScheduleRequest\x1a\x17.schedule.ScheduleEntry\x12I\n\x0e\x44\x65leteSchedule\x12\x15.schedule.DateRequest\x1a .schedule.DeleteScheduleResponse\x12G\n\x11GetBestRatedMovie\x12\x15.schedule.DateRequest\x1a\x1b.schedule.BestRatedResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schedule_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATEREQUEST']._serialized_start=57
  _globals['_DATEREQUEST']._serialized_end=84
  _globals['_SCHEDULEENTRY']._serialized_start=86
  _globals['_SCHEDULEENTRY']._serialized_end=131
  _globals['_LISTSCHEDULESRESPONSE']._serialized_start=133
  _globals['_LISTSCHEDULESRESPONSE']._serialized_end=200
  _globals['_CREATESCHEDULEREQUEST']._serialized_start=202
  _globals['_CREATESCHEDULEREQUEST']._serialized_end=255
  _globals['_UPDATESCHEDULEREQUEST']._serialized_start=257
  _globals['_UPDATESCHEDULEREQUEST']._serialized_end=310
  _globals['_DELETESCHEDULERESPONSE']._serialized_start=312
  _globals['_DELETESCHEDULERESPONSE']._serialized_end=418
  _globals['_MOVIE']._serialized_start=420
  _globals['_MOVIE']._serialized_end=488
  _globals['_BESTRATEDRESPONSE']._serialized_start=490
  _globals['_BESTRATEDRESPONSE']._serialized_end=588
  _globals['_SCHEDULE']._serialized_start=591
  _globals['_SCHEDULE']._serialized_end=1046
# @@protoc_insertion_point(module_scope)
